### ISSUE TITLE
Неплохо бы выровнять код

### ISSUE THREAD

**Issue by coursar** [protpolymer/sportmaster-bonus#10]
https://github.com/protpolymer/sportmaster-bonus/blob/79f1dd368e66fb57564b8fa27b6dd9b61fe51256/src/main/java/ru/itpark/BonusService.java#L22-L27

Ctrl + Alt + L в IDEA

**Comment by protpolymer** [comment]
Выполнено 6bd47d670e267346723f0668382121492f87acdf
