### ISSUE TITLE
Зачем double?

### ISSUE THREAD

**Issue by coursar** [protpolymer/sportmaster-bonus#5]
https://github.com/protpolymer/sportmastrer-bonus/blob/00038d5d31bc2c2c9382aafb05ec2fceaad8cdf3/src/main/java/ru/itpark/BonusService.java#L4

**Comment by protpolymer** [comment]
предполагалось, что сумма покупок может иметь не только целочисленные значения. После анализа условия стало понятно, что дробная часть все равно бы не учитывалась. Изменил тип данных с double на int
