### ISSUE TITLE
Старайтесь давать имена проектам без ошибок

### ISSUE THREAD

**Issue by coursar** [protpolymer/sportmaster-bonus#7]
'sportmaster-bonus' а не 'sportmastrer-bonus'

**Comment by protpolymer** [comment]
не могу найти, где можно исправить

**Comment by coursar** [comment]
![repository-rename](https://user-images.githubusercontent.com/3601892/48951320-f23fd000-ef5f-11e8-9c6e-40ddebc6d757.png)

**Comment by protpolymer** [comment]
Исправлено
