### ISSUE TITLE
Приведение к int избыточно

### ISSUE THREAD

**Issue by coursar** [protpolymer/sportmaster-bonus#8]
https://github.com/protpolymer/sportmaster-bonus/blob/84b2847a04cf043a3f8ddd8220f4ef033346d8fc/src/main/java/ru/itpark/BonusService.java#L23
https://github.com/protpolymer/sportmaster-bonus/blob/84b2847a04cf043a3f8ddd8220f4ef033346d8fc/src/main/java/ru/itpark/BonusService.java#L28
https://github.com/protpolymer/sportmaster-bonus/blob/84b2847a04cf043a3f8ddd8220f4ef033346d8fc/src/main/java/ru/itpark/BonusService.java#L33

**Comment by protpolymer** [comment]
Исправлено
fac39892537d4b1330171ef398da0b29aac4b121
