### ISSUE TITLE
Используйте return вместо цепочки условий

### ISSUE THREAD

**Issue by coursar** [protpolymer/sportmaster-bonus#9]
https://github.com/protpolymer/sportmaster-bonus/blob/84b2847a04cf043a3f8ddd8220f4ef033346d8fc/src/main/java/ru/itpark/BonusService.java#L18
https://github.com/protpolymer/sportmaster-bonus/blob/84b2847a04cf043a3f8ddd8220f4ef033346d8fc/src/main/java/ru/itpark/BonusService.java#L23
https://github.com/protpolymer/sportmaster-bonus/blob/84b2847a04cf043a3f8ddd8220f4ef033346d8fc/src/main/java/ru/itpark/BonusService.java#L28
https://github.com/protpolymer/sportmaster-bonus/blob/84b2847a04cf043a3f8ddd8220f4ef033346d8fc/src/main/java/ru/itpark/BonusService.java#L33

Используйте return вместо цепочки условий.

**Comment by protpolymer** [comment]
исправлено fac39892537d4b1330171ef398da0b29aac4b121

**Comment by coursar** [comment]
Вместо
```java
        if (totalAmount == 0) {
            return 0;

        } else if (totalAmount <= maxBlueValue) {
            // blue card

            return purchaseAmount / 1000 * bonusBlue;

        } else if (totalAmount <= maxSilverValue) {
            // silver card

            return purchaseAmount / 1000 * bonusSilver;

        } else {
            // gold card

            return purchaseAmount / 1000 * bonusGold;
        }
```

Должно быть:
```java
        if (totalAmount == 0) {
            return 0;

        }

        if (totalAmount <= maxBlueValue) {
            // blue card

            return purchaseAmount / 1000 * bonusBlue;

        }

        if (totalAmount <= maxSilverValue) {
            // silver card

            return purchaseAmount / 1000 * bonusSilver;

        }

        // gold card
        return purchaseAmount / 1000 * bonusGold;
```

**Comment by protpolymer** [comment]
реализовано 79f1dd368e66fb57564b8fa27b6dd9b61fe51256
